#set_property IOSTANDARD LVCMOS25 [get_ports clk_in]
#set_property PACKAGE_PIN Y9 [get_ports clk_in]

#create_clock -period 10 -name clk [get_ports clk_in1]

set_property IOSTANDARD LVCMOS25 [get_ports reset]
set_property PACKAGE_PIN F22 [get_ports reset]

set_property IOSTANDARD LVCMOS25 [get_ports {SW[3]}]
set_property PACKAGE_PIN M15 [get_ports {SW[3]}]

set_property IOSTANDARD LVCMOS25 [get_ports {SW[2]}]
set_property PACKAGE_PIN H17 [get_ports {SW[2]}]

set_property IOSTANDARD LVCMOS25 [get_ports {SW[1]}]
set_property PACKAGE_PIN H18 [get_ports {SW[1]}]

set_property IOSTANDARD LVCMOS25 [get_ports {SW[0]}]
set_property PACKAGE_PIN H19 [get_ports {SW[0]}]


set_property IOSTANDARD LVCMOS25 [get_ports {number[7]}]
set_property PACKAGE_PIN U14 [get_ports {number[7]}]

set_property IOSTANDARD LVCMOS25 [get_ports {number[6]}]
set_property PACKAGE_PIN U19 [get_ports {number[6]}]

set_property IOSTANDARD LVCMOS25 [get_ports {number[5]}]
set_property PACKAGE_PIN W22 [get_ports {number[5]}]

set_property IOSTANDARD LVCMOS25 [get_ports {number[4]}]
set_property PACKAGE_PIN V22 [get_ports {number[4]}]

set_property IOSTANDARD LVCMOS25 [get_ports {number[3]}]
set_property PACKAGE_PIN U21 [get_ports {number[3]}]

set_property IOSTANDARD LVCMOS25 [get_ports {number[2]}]
set_property PACKAGE_PIN U22 [get_ports {number[2]}]

set_property IOSTANDARD LVCMOS25 [get_ports {number[1]}]
set_property PACKAGE_PIN T21 [get_ports {number[1]}]

set_property IOSTANDARD LVCMOS25 [get_ports {number[0]}]
set_property PACKAGE_PIN T22 [get_ports {number[0]}]

set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[11]}]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_0_m_axis_tvalid]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[24]}]
set_property MARK_DEBUG true [get_nets design_1_i/Net]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0_m_axis_tdata[22]}]

set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[9]}]

set_property MARK_DEBUG false [get_nets {design_1_i/dma_converter_0/keep[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0_keep[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0_keep[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0_keep[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0_keep[1]}]
set_property MARK_DEBUG false [get_nets design_1_i/dma_converter_0/last]
set_property MARK_DEBUG true [get_nets design_1_i/dma_converter_0_last]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/dma_converter_0/OutCnt[0]} {design_1_i/dma_converter_0/OutCnt[1]} {design_1_i/dma_converter_0/OutCnt[2]} {design_1_i/dma_converter_0/OutCnt[3]} {design_1_i/dma_converter_0/OutCnt[4]} {design_1_i/dma_converter_0/OutCnt[5]} {design_1_i/dma_converter_0/OutCnt[6]} {design_1_i/dma_converter_0/OutCnt[7]} {design_1_i/dma_converter_0/OutCnt[8]} {design_1_i/dma_converter_0/OutCnt[9]} {design_1_i/dma_converter_0/OutCnt[10]} {design_1_i/dma_converter_0/OutCnt[11]} {design_1_i/dma_converter_0/OutCnt[12]} {design_1_i/dma_converter_0/OutCnt[13]} {design_1_i/dma_converter_0/OutCnt[14]} {design_1_i/dma_converter_0/OutCnt[15]} {design_1_i/dma_converter_0/OutCnt[16]} {design_1_i/dma_converter_0/OutCnt[17]} {design_1_i/dma_converter_0/OutCnt[18]} {design_1_i/dma_converter_0/OutCnt[19]} {design_1_i/dma_converter_0/OutCnt[20]} {design_1_i/dma_converter_0/OutCnt[21]} {design_1_i/dma_converter_0/OutCnt[22]} {design_1_i/dma_converter_0/OutCnt[23]} {design_1_i/dma_converter_0/OutCnt[24]} {design_1_i/dma_converter_0/OutCnt[25]} {design_1_i/dma_converter_0/OutCnt[26]} {design_1_i/dma_converter_0/OutCnt[27]} {design_1_i/dma_converter_0/OutCnt[28]} {design_1_i/dma_converter_0/OutCnt[29]} {design_1_i/dma_converter_0/OutCnt[30]} {design_1_i/dma_converter_0/OutCnt[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axis_data_fifo_0_m_axis_tdata[0]} {design_1_i/axis_data_fifo_0_m_axis_tdata[1]} {design_1_i/axis_data_fifo_0_m_axis_tdata[2]} {design_1_i/axis_data_fifo_0_m_axis_tdata[3]} {design_1_i/axis_data_fifo_0_m_axis_tdata[4]} {design_1_i/axis_data_fifo_0_m_axis_tdata[5]} {design_1_i/axis_data_fifo_0_m_axis_tdata[6]} {design_1_i/axis_data_fifo_0_m_axis_tdata[7]} {design_1_i/axis_data_fifo_0_m_axis_tdata[8]} {design_1_i/axis_data_fifo_0_m_axis_tdata[9]} {design_1_i/axis_data_fifo_0_m_axis_tdata[10]} {design_1_i/axis_data_fifo_0_m_axis_tdata[11]} {design_1_i/axis_data_fifo_0_m_axis_tdata[12]} {design_1_i/axis_data_fifo_0_m_axis_tdata[13]} {design_1_i/axis_data_fifo_0_m_axis_tdata[14]} {design_1_i/axis_data_fifo_0_m_axis_tdata[15]} {design_1_i/axis_data_fifo_0_m_axis_tdata[16]} {design_1_i/axis_data_fifo_0_m_axis_tdata[17]} {design_1_i/axis_data_fifo_0_m_axis_tdata[18]} {design_1_i/axis_data_fifo_0_m_axis_tdata[19]} {design_1_i/axis_data_fifo_0_m_axis_tdata[20]} {design_1_i/axis_data_fifo_0_m_axis_tdata[21]} {design_1_i/axis_data_fifo_0_m_axis_tdata[22]} {design_1_i/axis_data_fifo_0_m_axis_tdata[23]} {design_1_i/axis_data_fifo_0_m_axis_tdata[24]} {design_1_i/axis_data_fifo_0_m_axis_tdata[25]} {design_1_i/axis_data_fifo_0_m_axis_tdata[26]} {design_1_i/axis_data_fifo_0_m_axis_tdata[27]} {design_1_i/axis_data_fifo_0_m_axis_tdata[28]} {design_1_i/axis_data_fifo_0_m_axis_tdata[29]} {design_1_i/axis_data_fifo_0_m_axis_tdata[30]} {design_1_i/axis_data_fifo_0_m_axis_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/dma_converter_0_keep[0]} {design_1_i/dma_converter_0_keep[1]} {design_1_i/dma_converter_0_keep[2]} {design_1_i/dma_converter_0_keep[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/axis_data_fifo_0_m_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/dma_converter_0/last]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/Net]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
