set_property SRC_FILE_INFO {cfile:/home/rui/workspace/R20180914_dmaconverter/pins.xdc rfile:../../../pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports reset]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {SW[3]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports {SW[2]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {SW[1]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports {SW[0]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {number[7]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {number[6]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22 [get_ports {number[5]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V22 [get_ports {number[4]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21 [get_ports {number[3]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U22 [get_ports {number[2]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T21 [get_ports {number[1]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports {number[0]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[18]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[11]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[21]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[16]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[3]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[0]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[29]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[30]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[2]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[27]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[15]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[22]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[7]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[23]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[28]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[6]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[8]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[13]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[19]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[24]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[12]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[31]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[20]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[25]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[26]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[5]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[14]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[10]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[4]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[1]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[17]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/dma_converter_0/OutCnt[9]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/dma_converter_0/keep[2]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/dma_converter_0/last]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/dma_converter_0/OutCnt[0]} {design_1_i/dma_converter_0/OutCnt[1]} {design_1_i/dma_converter_0/OutCnt[2]} {design_1_i/dma_converter_0/OutCnt[3]} {design_1_i/dma_converter_0/OutCnt[4]} {design_1_i/dma_converter_0/OutCnt[5]} {design_1_i/dma_converter_0/OutCnt[6]} {design_1_i/dma_converter_0/OutCnt[7]} {design_1_i/dma_converter_0/OutCnt[8]} {design_1_i/dma_converter_0/OutCnt[9]} {design_1_i/dma_converter_0/OutCnt[10]} {design_1_i/dma_converter_0/OutCnt[11]} {design_1_i/dma_converter_0/OutCnt[12]} {design_1_i/dma_converter_0/OutCnt[13]} {design_1_i/dma_converter_0/OutCnt[14]} {design_1_i/dma_converter_0/OutCnt[15]} {design_1_i/dma_converter_0/OutCnt[16]} {design_1_i/dma_converter_0/OutCnt[17]} {design_1_i/dma_converter_0/OutCnt[18]} {design_1_i/dma_converter_0/OutCnt[19]} {design_1_i/dma_converter_0/OutCnt[20]} {design_1_i/dma_converter_0/OutCnt[21]} {design_1_i/dma_converter_0/OutCnt[22]} {design_1_i/dma_converter_0/OutCnt[23]} {design_1_i/dma_converter_0/OutCnt[24]} {design_1_i/dma_converter_0/OutCnt[25]} {design_1_i/dma_converter_0/OutCnt[26]} {design_1_i/dma_converter_0/OutCnt[27]} {design_1_i/dma_converter_0/OutCnt[28]} {design_1_i/dma_converter_0/OutCnt[29]} {design_1_i/dma_converter_0/OutCnt[30]} {design_1_i/dma_converter_0/OutCnt[31]}]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axis_data_fifo_0_m_axis_tdata[0]} {design_1_i/axis_data_fifo_0_m_axis_tdata[1]} {design_1_i/axis_data_fifo_0_m_axis_tdata[2]} {design_1_i/axis_data_fifo_0_m_axis_tdata[3]} {design_1_i/axis_data_fifo_0_m_axis_tdata[4]} {design_1_i/axis_data_fifo_0_m_axis_tdata[5]} {design_1_i/axis_data_fifo_0_m_axis_tdata[6]} {design_1_i/axis_data_fifo_0_m_axis_tdata[7]} {design_1_i/axis_data_fifo_0_m_axis_tdata[8]} {design_1_i/axis_data_fifo_0_m_axis_tdata[9]} {design_1_i/axis_data_fifo_0_m_axis_tdata[10]} {design_1_i/axis_data_fifo_0_m_axis_tdata[11]} {design_1_i/axis_data_fifo_0_m_axis_tdata[12]} {design_1_i/axis_data_fifo_0_m_axis_tdata[13]} {design_1_i/axis_data_fifo_0_m_axis_tdata[14]} {design_1_i/axis_data_fifo_0_m_axis_tdata[15]} {design_1_i/axis_data_fifo_0_m_axis_tdata[16]} {design_1_i/axis_data_fifo_0_m_axis_tdata[17]} {design_1_i/axis_data_fifo_0_m_axis_tdata[18]} {design_1_i/axis_data_fifo_0_m_axis_tdata[19]} {design_1_i/axis_data_fifo_0_m_axis_tdata[20]} {design_1_i/axis_data_fifo_0_m_axis_tdata[21]} {design_1_i/axis_data_fifo_0_m_axis_tdata[22]} {design_1_i/axis_data_fifo_0_m_axis_tdata[23]} {design_1_i/axis_data_fifo_0_m_axis_tdata[24]} {design_1_i/axis_data_fifo_0_m_axis_tdata[25]} {design_1_i/axis_data_fifo_0_m_axis_tdata[26]} {design_1_i/axis_data_fifo_0_m_axis_tdata[27]} {design_1_i/axis_data_fifo_0_m_axis_tdata[28]} {design_1_i/axis_data_fifo_0_m_axis_tdata[29]} {design_1_i/axis_data_fifo_0_m_axis_tdata[30]} {design_1_i/axis_data_fifo_0_m_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/dma_converter_0_keep[0]} {design_1_i/dma_converter_0_keep[1]} {design_1_i/dma_converter_0_keep[2]} {design_1_i/dma_converter_0_keep[3]}]]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/axis_data_fifo_0_m_axis_tvalid]]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/dma_converter_0/last]]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/Net]]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
